// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6135.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc.team6135.robot.Robot;

/**
 *
 */
public class pivotRobot extends Command {

    private double m_t;
    private double b;
    public pivotRobot(double t) {
        m_t = t/180.0*2*Math.PI;
        if(t<0)
        {
        	b=-1;
        }
        else
        {
        	b=1;
        }
        requires(Robot.drivetrain);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.drivetrain.set(b*0.6,-b*0.6);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.drivetrain.getLeftDistance()>=m_t;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
